@baseUrl = http://localhost:8081

### Main page
GET {{baseUrl}}/

### Load products
POST {{baseUrl}}/products/load?sortBy=id&order=asc&page=0&pageSize=10

### Get products
GET {{baseUrl}}/products?sortBy=id&order=asc&page=0&pageSize=10

### Get products - different sorting
GET {{baseUrl}}/products?sortBy=title&order=asc&page=0&pageSize=10
GET {{baseUrl}}/products?sortBy=price&order=desc&page=0&pageSize=50
GET {{baseUrl}}/products?sortBy=id&order=asc&page=1&pageSize=10

### Add product
POST {{baseUrl}}/products?sortBy=id&order=asc&page=0&pageSize=10
Content-Type: application/x-www-form-urlencoded

title=Test Product&price=99.99&vendor=Test Vendor

### Search
GET {{baseUrl}}/search
GET {{baseUrl}}/products/search?query=test&sortBy=id&order=asc&page=0&pageSize=10

### Edit product (change the id)
GET {{baseUrl}}/products/1/edit

POST {{baseUrl}}/products/1/update
Content-Type: application/x-www-form-urlencoded

title=Updated Title&price=149.99&vendor=Updated Vendor

### Delete product (change the id)
POST {{baseUrl}}/products/1/delete?sortBy=id&order=asc&page=0&pageSize=10
